#+TITLE: Oh My Zsh

*Install [[https://github.com/ohmyzsh/ohmyzsh][Oh-My-Zsh]]*\\
A delightful community-driven framework for managing your zsh configuration.
#+begin_src sh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#+end_src

* Plugins
Oh My Zsh plugins allow you to add functionality of many sorts to your shell just by enabling them. [[https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins][Plugins]]

*[[https://github.com/zsh-users/zsh-autosuggestions][Zsh Autosuggestions]]*\\
It suggests commands as you type based on history and completions.
#+begin_src sh
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#+end_src

*[[https://github.com/zsh-users/zsh-completions][Zsh Completions]]*\\
Additional completion definitions for Zsh.
#+begin_src sh
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
autoload -U compinit && compinit
#+end_src

*[[https://github.com/zsh-users/zsh-syntax-highlighting][Zsh Syntax Highlighting]]*\\
This package provides syntax highlighting for the shell zsh. It enables highlighting of commands whilst they are typed at a zsh prompt into an interactive terminal. This helps in reviewing commands before running them, particularly in catching syntax errors.

#+begin_src sh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#+end_src

*Enable zsh plugins*
#+begin_src bash
plugins=(
  git ruby rails yarn
  zsh-autosuggestions zsh-syntax-highlighting
)
#+end_src

* Alias
*Show folder structure with tree view*\\
The tree view looks like:
#+begin_src bash
➜  Desktop tree
.
|____.DS_Store
|____test
| |____ror20h.rb
|____.localized
|____20min.rb
#+end_src

#+begin_src bash
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
#+end_src

* Exports
*Set http(s) proxy for command line*\\
You may want to disable it if you're not using a VPN, or change the port.
#+begin_src bash
export http_proxy=http://127.0.0.1:1087
export https_proxy=http://127.0.0.1:1087
#+end_src

* Functions
*Git add commit*\\
The lines inside function use aliases from oh-my-zsh git plugin.
#+begin_src sh
function gac () {
  gaa
  gcmsg "$1"
}
#+end_src

* Configurations
For more configurations, please visit [[https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template][zshrc-template]]

*For more themes, please visit: [[https://github.com/ohmyzsh/ohmyzsh/wiki/Themes][oh-my-zsh-themes]]*
#+begin_src bash
ZSH_THEME='robbyrussell'
#+end_src

*Disable auto-setting terminal title*
#+begin_src bash
DISABLE_AUTO_TITLE='true'
#+end_src

*Automatically update without prompting*\\
Sometimes the update prompt is annoying because it breaks the command you run when launching the Terminal.
#+begin_src bash
DISABLE_UPDATE_PROMPT="true"
#+end_src

*Add and reload Oh-My-Zsh configurations*
#+begin_src sh
cat command-line-tools/.zshrc >> ~/.zshrc
source ~/.zshrc
#+end_src
echo 'Command Line Tool -> Zsh Configuration Mangament Tool: Oh-My-Zsh'
echo '  Install Oh-My-Zsh'
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo '  Install Oh-My-Zsh plugin: Zsh Autosuggestions'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo '  Install Oh-My-Zsh plugin: Zsh Completions'
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
autoload -U compinit && compinit

echo '  Install Oh-My-Zsh plugin: Zsh Syntax Highlighting'
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo '  Move Oh-My-Zsh configurations to home folder'
cp -R .zshrc ~/.zshrc

echo '  Reload Oh-My-Zsh configurations'
source ~/.zshrc

