#+TITLE: Zsh
* Oh My Zsh
Install [[https://github.com/ohmyzsh/ohmyzsh][Oh-My-Zsh]] a delightful community-driven framework for managing your zsh configuration.
#+begin_src sh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#+end_src

For more configurations, please visit [[https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template][zshrc-template]]\\
For more themes, please visit: [[https://github.com/ohmyzsh/ohmyzsh/wiki/Themes][oh-my-zsh-themes]]
#+begin_src bash
ZSH_THEME='robbyrussell'
#+end_src

Disable auto-setting terminal title.
#+begin_src bash
DISABLE_AUTO_TITLE='true'
#+end_src

Automatically update without prompting. Sometimes the update prompt is annoying because it breaks the command you run when launching the Terminal.
#+begin_src bash
DISABLE_UPDATE_PROMPT="true"
#+end_src

* Alias
Alias git diff as diff for rich color and styles.
#+begin_src bash
alias diff="git diff --no-index"
#+end_src

* Exports
Set http(s) proxy for command line. You may want to disable it if you're not using a VPN, or change the port.
#+begin_src bash
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
#+end_src

Make non-ASCII characters display right.
#+begin_src bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
#+end_src

* Functions

* Plugins
Oh My Zsh plugins allow you to add functionality of many sorts to your shell just by enabling them. [[https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins][Plugins]]

Enable zsh plugins:
#+begin_src bash
plugins=(
  git
  zsh-autosuggestions zsh-completions zsh-syntax-highlighting
)
#+end_src

** Zsh Autosuggestions 
[[https://github.com/zsh-users/zsh-autosuggestions][Zsh Autosuggestions]]: It suggests commands as you type based on history and completions.
#+begin_src sh
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#+end_src

Speeds up pasting with autosuggest.
# https://github.com/zsh-users/zsh-autosuggestions/issues/238
#+begin_src bash
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
#+end_src

Clear suggestion after pasting.
# https://github.com/zsh-users/zsh-autosuggestions/issues/351
#+begin_src bash
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)
#+end_src

** Zsh Completions 
[[https://github.com/zsh-users/zsh-completions][Zsh Completions]]: Additional completion definitions for Zsh.
#+begin_src sh
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
autoload -U compinit && compinit
#+end_src

** Zsh Syntax Highlighting
[[https://github.com/zsh-users/zsh-syntax-highlighting][Zsh Syntax Highlighting]]: This package provides syntax highlighting for the shell zsh. It enables highlighting of commands whilst they are typed at a zsh prompt into an interactive terminal. This helps in reviewing commands before running them, particularly in catching syntax errors.

#+begin_src sh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#+end_src

