#+TITLE: The Productive MacOS
NOTICE: This project is on building, use it as your own risk.

A minimal and productive macOS configration with a good documentation that you can live with for a long time.
This is a source code with documentation repo especially for programmers, if you need explaination with pictures, please visit
https://book.willbc.cn/the-productive-macos/

* Table of Contents
| [[#command-line-tools][Command Line Tools]] | [[#applications][Applications]] | [[#system-preferences][System Preferences]]     |
|--------------------+--------------+------------------------|
| [[#oh-my-zsh][Oh My Zsh]]          | [[./applications/alfred.org][Alfred]]       | [[./system-preferences/general.org][General]]                |
| [[./command-line-tools/brew.org][Brew]]               | [[./applications/emacs.org][Emacs]]        | [[#desktop--screen-saver][Desktop & Screen Saver]] |
| [[#git][Git]]                | [[./applications/chrome.org][Chrome]]       | [[#dock][Dock]]                   |
| [[#node][Node]]               | [[./applications/terminal.org][Terminal]]     | [[#accessbility][Accessbility]]           |
| [[#ruby][Ruby]]               | [[./applications/finder.org][Finder]]       | [[#security--privacy][Security & Privacy]]     |
| [[#trash][Trash]]              | [[./applications/rubymine.org][Rubymine]]     | [[#keyboard][Keyboard]]               |
|                    | [[#xcode][Xcode]]        | [[#trackpad][Trackpad]]               |
|                    | [[./applications/font-book.org][Font Book]]    | [[#displays][Displays]]               |
|                    |              | [[#battery][Battery]]                |

All Rights Reserved

* Install
Please read this documentation through before running the command below.
#+begin_src bash
git clone https://github.com/willbchang/macos-dotfiles.git
sh macos-dotfiles/install.sh
#+end_src
* Command Line Tools
* System Preferences
** Dock
*Set the icon size of Dock items to 72 pixels*
#+begin_src sh
defaults write com.apple.dock tilesize -int 72
#+end_src

*Enable magnification*
#+begin_src sh
defaults write com.apple.dock magnification -bool true
#+end_src

*Set magnification size to 100*
#+begin_src sh
defaults write com.apple.dock largesize -int 100
#+end_src

*Change dock position to left*
#+begin_src sh
defaults write com.apple.dock orientation -string "left"
#+end_src

*Change minimize/maximize window effect*
#+begin_src sh
defaults write com.apple.dock mineffect -string "scale"
#+end_src

*Minimize windows into their application’s icon*
#+begin_src sh
defaults write com.apple.dock minimize-to-application -bool true
#+end_src

*Don’t animate opening applications from the Dock*
#+begin_src sh
defaults write com.apple.dock launchanim -bool false
#+end_src

*Automatically hide and show the Dock*
#+begin_src sh
defaults write com.apple.dock autohide -bool true
#+end_src

*Remove the auto-hiding Dock delay*
#+begin_src sh
defaults write com.apple.dock autohide-delay -float 0
#+end_src

*Remove the animation when hiding/showing the Dock*
#+begin_src sh
defaults write com.apple.dock autohide-time-modifier -float 0
#+end_src

*Show indicator lights for open applications in the Dock*
#+begin_src sh
defaults write com.apple.dock show-process-indicators -bool true
#+end_src

*Don’t show recent applications in Dock*
#+begin_src sh
defaults write com.apple.dock show-recents -bool false
#+end_src

*Show only open applications in the Dock*
#+begin_src sh
defaults write com.apple.dock static-only -bool true
#+end_src

*Make Dock icons of hidden applications translucent*
#+begin_src sh
defaults write com.apple.dock showhidden -bool true
#+end_src

*Remove all (default) app icons from the Dock*\\
This is only really useful when setting up a new Mac, or if you don’t use the Dock to launch apps.
#+begin_src sh
defaults write com.apple.dock persistent-apps -array
#+end_src

*Enable spring loading for all Dock items*
#+begin_src sh
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true
#+end_src

*Enable highlight hover effect for the grid view of a stack (Dock)*
#+begin_src sh
defaults write com.apple.dock mouse-over-hilite-stack -bool true
#+end_src

*Add a spacer to the left side of the Dock (where the applications are)*
#+begin_src sh
defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
#+end_src

*Add a spacer to the right side of the Dock (where the Trash is)*
#+begin_src sh
defaults write com.apple.dock persistent-others -array-add '{tile-data={}; tile-type="spacer-tile";}'
#+end_src
** Accessbility
*Enable Option + Esc to speak selected text*
#+begin_src sh
defaults write com.apple.speech.synthesis.general.prefs SpokenUIUseSpeakingHotKeyFlag -bool true
#+end_src

*Set Samantha to the default speaker*
#+begin_src sh
defaults write com.apple.speech.voice.prefs SelectedVoiceCreator -int 1886745202
defaults write com.apple.speech.voice.prefs SelectedVoiceID -int 184844483
defaults write com.apple.speech.voice.prefs SelectedVoiceName -string "Samantha"
#+end_src

*Enable three finger drag*
#+begin_src sh
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture -int 2
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerVertSwipeGesture -int 0
defaults write com.apple.AppleMultitouchTrackpad DragLock -bool false
#+end_src

** Security & Privacy
*Allow apps downloaded from anywhere*
#+begin_src sh
sudo spctl --master-disable
#+end_src
** Keyboard
*** Keyboard
*Disable press-and-hold for keys in favor of key repeat*
#+begin_src sh
defaults write -g ApplePressAndHoldEnabled -bool false
#+end_src

*Set fast keyboard repeat rate*\\
TODO: Set InitialKeyRepeat integer range
#+begin_src sh
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15
#+end_src

*Set touchbar(control strip) icons*
#+begin_src sh
defaults write com.apple.controlstrip FullCustomized '(
    "com.apple.system.group.media",
    NSTouchBarItemIdentifierFlexibleSpace,
    "com.apple.system.volume",
    "com.apple.system.mute",
    NSTouchBarItemIdentifierFlexibleSpace,
    "com.apple.system.brightness",
    "com.apple.system.night-shift",
    NSTouchBarItemIdentifierFlexibleSpace,
    "com.apple.system.screen-lock",
    "com.apple.system.notification-center"
)'
#+end_src

*Expaned control strip by default*
#+begin_src sh
defaults write com.apple.touchbar.agent PresentationModeGlobal -string "fullControlStrip"
#+end_src

*** Text
*Disable automatic capitalization*
#+begin_src sh
defaults write -g NSAutomaticCapitalizationEnabled -bool false
#+end_src

*Disable smart dashes*
#+begin_src sh
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
#+end_src

*Disable automatic period substitution*
#+begin_src sh
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
#+end_src

*Disable smart quotes*
#+begin_src sh
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
#+end_src

*Disable auto-correct*
#+begin_src sh
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
#+end_src

*** Shortcuts
*Enable full keyboard access for all controls*\\
(e.g. enable Tab in modal dialogs)
#+begin_src sh
defaults write -g AppleKeyboardUIMode -int 3
#+end_src

*Disable shortcuts to Turn Dock Hiding On/Off*
#+begin_src sh
/usr/libexec/PlistBuddy -c "set :AppleSymbolicHotKeys:52:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
#+end_src

*Disable shortcuts to Select the previous input source*
#+begin_src sh
/usr/libexec/PlistBuddy -c "set :AppleSymbolicHotKeys:60:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
#+end_src

*Disable shortcuts to Select next source in input menu*
#+begin_src sh
/usr/libexec/PlistBuddy -c "set :AppleSymbolicHotKeys:61:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
#+end_src

*Disable shortcuts to Show Spotlight Search*
#+begin_src sh
/usr/libexec/PlistBuddy -c "set :AppleSymbolicHotKeys:64:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
#+end_src

*Disable shortcuts to Show Finder search window*
#+begin_src sh
/usr/libexec/PlistBuddy -c "set :AppleSymbolicHotKeys:65:enabled false" ~/Library/Preferences/com.apple.symbolichotkeys.plist
#+end_src
*** Input Sources
*Disable Show Input menu in menu bar*
#+begin_src sh
defaults write com.apple.TextInputMenu visible -bool false
#+end_src
** Trackpad
*Enable tap to click*
#+begin_src sh
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
#+end_src

*Enable tap with three fingers to Look up & data detectors*
#+begin_src sh
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerTapGesture -int 2
#+end_src
** Displays
*Enable Night Shift*\\
[[./system-preferences/displays-night-shift.scpt][displays-night-shift.scpt]]
#+begin_src sh
osascript system-preferences/displays-night-shift.scpt
#+end_src
** Battery
*Show battery percentage in menu bar*
#+begin_src sh
defaults write com.apple.menuextra.battery ShowPercent YES
#+end_src
