 #+TITLE: Emacs
* Emacs Mac Port
*Install [[https://github.com/railwaycat/homebrew-emacsmacport][emacs-mac]]*\\
This provides a native GUI support for Mac OS X 10.6 - macOS 10.15.
#+begin_src sh
brew tap railwaycat/emacsmacport
brew cask install emacs-mac
#+end_src
* Doom Emacs
** Installation
*Install doom emacs*
#+begin_src sh
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
#+end_src

** Dependencies
*Install doom emacs dependencies: ripgrep, coreutils, fd*
#+begin_src sh
brew install ripgrep
brew install coreutils
brew install fd
#+end_src

*Install markdown preview depenencies: pandoc*
#+begin_src sh
brew install pandoc
#+end_src

*Install vterm dependencies: cmake, libvterm*
#+begin_src sh
brew install cmake
brew install libvterm
#+end_src

*Install shell mode dependencies: shfmt, shellcheck*
#+begin_src sh
brew install shfmt
brew install shellcheck
#+end_src

** Setup
*Setup doom emacs for macos*
#+begin_src sh
curl -Sso ~/.doom.d/README.org https://raw.githubusercontent.com/willbchang/macos-emacs-doom.d/master/README.org
echo "(org-babel-load-file \"~/.doom.d/README.org\")" >>~/.doom.d/config.el
#+end_src

*Copy init.el and packages.el to doom folder.*
#+begin_src sh
cp emacs/init.el ~/.config/doom/init.el
cp emacs/packages.el ~/.config/doom/packages.el
#+end_src

*Rebuild doom emacs packages*
#+begin_src sh
~/.emacs.d/bin/doom sync && ~/.emacs.d/bin/doom build
#+end_src

* Init.el
** completion
*company*: the ultimate code completion backend
*ivy*: a search engine for love and life

** ui
*doom*: what makes DOOM look the way it does
*hl-todo*: highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
*modeline*: snazzy, Atom-inspired modeline, plus API
*ophints*: highlight the region an operation acts on
*(popup +defaults)*: tame sudden yet inevitable temporary windows
*unicode*: extended unicode support for various languages
*vc-gutter*: vcs diff in the fringe
*vi-tilde-fringe*: fringe tildes to mark beyond EOB
*workspaces*: tab emulation, persistence & separate workspaces

** editor
*(evil +everywhere)*: come to the dark side, we have cookies
*file-templates*: auto-snippets for empty files
*fold*: (nigh) universal code folding
*multiple-cursors*: editing in many places at once
*snippets*: my elves. They type so I don't have to
*word-wrap*: soft wrapping with language-aware indent

** emacs
*dired*: making dired pretty [functional]
*electric*: smarter, keyword-based electric-indent
*undo*: persistent, smarter undo for your inevitable mistakes
*vc*: version-control and Emacs, sitting in a tree

** term
*vterm*: the best terminal emulation in Emacs

** checkers
*syntax*: tasing you for every semicolon you forget

** tools
*(eval +overlay)*: run code, run (also, repls)
*lookup*: navigate your code and its documentation
*magit*: a git porcelain for Emacs

** os
*(:if IS-MAC macos)*: improve compatibility with macOS
*tty*: improve the terminal Emacs experience

** lang
*emacs-lisp*: drown in parentheses
*markdown*: writing docs for people to ignore
*org*: organize your plain life in plain text

** config
(default +bindings +smartparens))

* Packages.el
** Org Superstar
[[https://github.com/integral-dw/org-superstar-mode][Org Superstar]] prettifies headings and plain lists in Org mode.
#+begin_src emacs-lisp
(package! org-superstar)
#+end_src

* Config.el
** UI
*** Title Bar
Show full path in title bar.
#+begin_src emacs-lisp
(setq frame-title-format
    '(:eval
       (if buffer-file-name
           (abbreviate-file-name buffer-file-name)
           "%b")))
#+end_src

*** Side Bar
TODO
*** Tab Bar
TODO
*** Status Bar
Hide the buffer name in doom-modeline
#+begin_src emacs-lisp
(after! doom-modeline
  (doom-modeline-def-segment buffer-info
    "buffer info segment."
    "")
  (doom-modeline-def-segment buffer-info-simple
    "simple buffer info segment."
    "")
  (setq doom-modeline-buffer-encoding nil)
  (setq doom-modeline-indent-info t)
  (setq column-number-mode t)
)
#+end_src

*** Window Size
Set window size to 80 x 36.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(width . 80))
(add-to-list 'default-frame-alist '(height . 36))
#+end_src

*** Color Theme
Use doom vibrant as default theme.
#+begin_src emacs-lisp
(setq doom-theme 'doom-vibrant)
#+end_src

*** Font
Set font family and font size.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Inconsolata" :size 20))
#+end_src

*** Line Number
| Display Style                | Value     | Status   |
|------------------------------+-----------+----------|
| Absolute line numbers        | t         | Default  |
| Relative line numbers        | 'relative | Prefered |
| Relative visual line numbers | 'visual   |          |
| No line numbers              | nil       |          |
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Keybinding

** Window Management

** Terminal
