#+TITLE: Dock & Menu Bar

* Dock
*Set the icon size of Dock items to 72 pixels*
#+begin_src sh
defaults write com.apple.dock tilesize -int 72
#+end_src

*Enable magnification*
#+begin_src sh
defaults write com.apple.dock magnification -bool true
#+end_src

*Set magnification size to 100*
#+begin_src sh
defaults write com.apple.dock largesize -int 100
#+end_src

*Change dock position to left*
#+begin_src sh
defaults write com.apple.dock orientation -string "left"
#+end_src

*Change minimize/maximize window effect*
| Options      | Values |
|--------------+--------|
| Scale effect | scale  |
| Genie effect | genie  |
#+begin_src sh
defaults write com.apple.dock mineffect -string "scale"
#+end_src

Double-click a window's title bar to zoom.
| Options  | Values   |
|----------+----------|
| minimize | Minimize |
| zoom     | Maximize |
#+begin_src sh
defaults write -g AppleActionOnDoubleClick -string "Maximize"
#+end_src

*Minimize windows into their application’s icon*
#+begin_src sh
defaults write com.apple.dock minimize-to-application -bool true
#+end_src

*Don’t animate opening applications from the Dock*
#+begin_src sh
defaults write com.apple.dock launchanim -bool false
#+end_src

*Automatically hide and show the Dock*
#+begin_src sh
defaults write com.apple.dock autohide -bool true
#+end_src

Don't show indicators for open applications.
#+begin_src sh
defaults write com.apple.dock show-process-indicators -bool false
#+end_src

Don’t show recent applications in Dock.
#+begin_src sh
defaults write com.apple.dock show-recents -bool false
#+end_src

** Hidden Features
*Remove the auto-hiding Dock delay*
#+begin_src sh
defaults write com.apple.dock autohide-delay -float 0
#+end_src

*Remove the animation when hiding/showing the Dock*
#+begin_src sh
defaults write com.apple.dock autohide-time-modifier -float 0
#+end_src

*Show only open applications in the Dock*
#+begin_src sh
defaults write com.apple.dock static-only -bool true
#+end_src

*Make Dock icons of hidden applications translucent*
#+begin_src sh
defaults write com.apple.dock showhidden -bool true
#+end_src

*Remove all (default) app icons from the Dock*\\
This is only really useful when setting up a new Mac, or if you don’t use the Dock to launch apps.
#+begin_src sh
defaults write com.apple.dock persistent-apps -array
#+end_src

*Enable spring loading for all Dock items*
#+begin_src sh
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true
#+end_src

*Enable highlight hover effect for the grid view of a stack (Dock)*
#+begin_src sh
defaults write com.apple.dock mouse-over-hilite-stack -bool true
#+end_src

* Menu Bar
Automatically hide and show the menu bar.
#+begin_src sh
defaults write -g _HIHideMenuBar -bool true
#+end_src

** Control Center
Show Wi-Fi in Menu Bar.
#+begin_src sh
defaults write com.apple.controlcenter "NSStatusItem Visible WiFi" -bool true
#+end_src

Don't show Bluetooth in menu bar.
#+begin_src sh
defaults write com.apple.controlcenter "NSStatusItem Visible Bluetooth" -bool false
#+end_src

Don't show AirDrop in menu bar.
#+begin_src sh
defaults write com.apple.controlcenter "NSStatusItem Visible AirDrop" -bool false
#+end_src


Don't show Do Not Disturb in menu bar.
| Status    | Options     | Values | Note                    |
|-----------+-------------+--------+-------------------------|
| Unchecked | always      |     24 | always not work for now |
| Checked   | always      |     18 | could be 16             |
| Unchecked | when active |      8 |                         |
| Checked   | when active |      2 |                         |
#+begin_src sh
defaults -currentHost write com.apple.controlcenter DoNotDisturb -int 8
# Unneed the code below for macOS 11.1
# defaults write com.apple.controlcenter "NSStatusItem Visible DoNotDisturb" -bool false
#+end_src

Don't show Keyboard Brightness in menu bar.
#+begin_src sh
defaults write com.apple.controlcenter "NSStatusItem Visible KeyboardBrightness" -bool false
#+end_src

Show Screen Mirroring in Menu Bar when active.
#+begin_src sh
defaults -currentHost write com.apple.controlcenter ScreenMirroring -int 2
defaults write com.apple.airplay showInMenuBarIfPresent -bool true
#+end_src

Show Display in Menu bar when active.
#+begin_src sh
defaults -currentHost write com.apple.controlcenter Display -int 2
#+end_src

Don't show Sound in Menu Bar.
#+begin_src sh
defaults -currentHost write com.apple.controlcenter Sound -int 8
#+end_src

** Other Modules
** Menu Bar Only
